### ISSUE TITLE
were iz thé andoid verzion

### ISSUE THREAD

**Issue by luizao-rizz** [liuk7071/ChonkyStation#13]
see title😭

**Comment by moonacutie** [comment]
pls make a ios version too

**Comment by skylersaleh** [comment]
Maybe if the dev wasn't too busy watching weird maid anime then it would run on android.

**Comment by skylersaleh** [comment]
Oh, wait, sorry... wrong project. Plz disregard.

**Comment by zFalconTB** [comment]
It will happen with the 4th rewrite surely

**Comment by liuk7071** [comment]
There already is a "rewrite_android" branch  guys

**Comment by zFalconTB** [comment]
Does crash bandicoot work there?

**Comment by liuk7071** [comment]
👺
